# Generated by Django 5.2.7 on 2026-10-09 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='estimate',
        ),
        migrations.RemoveField(
            model_name='estimateline',
            name='estimate',
        ),
        migrations.RemoveField(
            model_name='estimateline',
            name='bom_source_item',
        ),
        migrations.RemoveField(
            model_name='estimateline',
            name='client',
        ),
        migrations.RemoveField(
            model_name='estimateline',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='estimateline',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='estimateline',
            name='item',
        ),
        migrations.RemoveField(
            model_name='estimateline',
            name='parent_line',
        ),
        migrations.RemoveField(
            model_name='estimateline',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='Estimate',
        ),
        migrations.DeleteModel(
            name='EstimateLine',
        ),
    ]
