# Generated by Django 5.2.7 on 2026-10-07 04:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('masters', '0008_fabric_items'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobWorkOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('legacy_id', models.TextField(blank=True, db_index=True, null=True)),
                ('jwo_no', models.TextField(db_index=True)),
                ('process', models.TextField(default='')),
                ('vendor_name', models.TextField(default='')),
                ('order_date', models.DateField()),
                ('planned_qty', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('expected_completion', models.DateField(blank=True, null=True)),
                ('status', models.TextField(choices=[('Draft', 'Draft'), ('In-Process', 'In-Process'), ('Completed', 'Completed')], default='In-Process')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='masters.party')),
            ],
            options={
                'db_table': 'jobwork_orders',
                'ordering': ['-order_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JWOCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.TextField(default='')),
                ('description', models.TextField(blank=True, null=True)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('qty', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.TextField(default='Active')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job_work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='jobwork.jobworkorder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobwork_charges',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='JWOInward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('no', models.TextField(default='')),
                ('date', models.DateField()),
                ('qty', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('accepted', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('rejected', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('challan_no', models.TextField(blank=True, null=True)),
                ('status', models.TextField(default='Received')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job_work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inwards', to='jobwork.jobworkorder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobwork_inwards',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JWOMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('fabric_item', models.TextField(default='')),
                ('fabric_quality', models.TextField(default='')),
                ('shade', models.TextField(blank=True, null=True)),
                ('lot_no', models.TextField(blank=True, null=True)),
                ('qty', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job_work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='jobwork.jobworkorder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobwork_materials',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='JWOOutward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('no', models.TextField(default='')),
                ('date', models.DateField()),
                ('qty', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('lr_no', models.TextField(blank=True, null=True)),
                ('transporter', models.TextField(blank=True, null=True)),
                ('status', models.TextField(default='Sent')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job_work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outwards', to='jobwork.jobworkorder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobwork_outwards',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('legacy_id', models.TextField(blank=True, db_index=True, null=True)),
                ('plan_no', models.TextField(db_index=True)),
                ('date', models.DateField()),
                ('process', models.TextField()),
                ('process_category', models.TextField(blank=True, null=True)),
                ('vendor_name', models.TextField(default='')),
                ('fabric_item', models.TextField(default='')),
                ('fabric_quality', models.TextField(default='')),
                ('shade', models.TextField(blank=True, null=True)),
                ('expected_qty', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('expected_loss', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('expected_return_qty', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('status', models.TextField(choices=[('Active', 'Active'), ('Draft', 'Draft'), ('Completed', 'Completed')], default='Active')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobwork_process_plans',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='jobworkorder',
            name='process_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_work_orders', to='jobwork.processplan'),
        ),
        migrations.AddIndex(
            model_name='processplan',
            index=models.Index(fields=['client', '-date'], name='ix_jobwork_plan_date'),
        ),
        migrations.AddIndex(
            model_name='processplan',
            index=models.Index(fields=['client', 'status'], name='ix_jobwork_plan_status'),
        ),
        migrations.AddConstraint(
            model_name='processplan',
            constraint=models.UniqueConstraint(fields=('client', 'plan_no'), name='uq_jobwork_plan_no'),
        ),
        migrations.AddIndex(
            model_name='jobworkorder',
            index=models.Index(fields=['client', '-order_date'], name='ix_jobwork_order_date'),
        ),
        migrations.AddIndex(
            model_name='jobworkorder',
            index=models.Index(fields=['client', 'status'], name='ix_jobwork_order_status'),
        ),
        migrations.AddConstraint(
            model_name='jobworkorder',
            constraint=models.UniqueConstraint(fields=('client', 'jwo_no'), name='uq_jobwork_jwo_no'),
        ),
    ]
