# Generated by Django 5.2.7 on 2026-10-07 04:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('jobwork', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProcessInstruction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('legacy_id', models.TextField(blank=True, db_index=True, null=True)),
                ('pi_number', models.TextField(db_index=True)),
                ('po_id', models.TextField(blank=True, null=True)),
                ('po_number', models.TextField(blank=True, null=True)),
                ('vendor_id', models.TextField(blank=True, null=True)),
                ('vendor', models.TextField(default='')),
                ('fabric', models.TextField(default='')),
                ('fabric_sku', models.TextField(blank=True, null=True)),
                ('process_type', models.TextField(default='')),
                ('assigned_employee', models.TextField(blank=True, null=True)),
                ('assigned_qty', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('produced_qty', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('date', models.DateField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expected_completion_date', models.DateField(blank=True, null=True)),
                ('status', models.TextField(choices=[('Pending', 'Pending'), ('Draft', 'Draft'), ('In Progress', 'In Progress'), ('Running', 'Running'), ('Partially Completed', 'Partially Completed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='In Progress')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobwork_process_instructions',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VPIProgressEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('produced_qty', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('entered_by', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='jobwork.vendorprocessinstruction')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobwork_pi_entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vendorprocessinstruction',
            index=models.Index(fields=['client', '-date'], name='ix_jobwork_pi_date'),
        ),
        migrations.AddIndex(
            model_name='vendorprocessinstruction',
            index=models.Index(fields=['client', 'status'], name='ix_jobwork_pi_status'),
        ),
        migrations.AddConstraint(
            model_name='vendorprocessinstruction',
            constraint=models.UniqueConstraint(fields=('client', 'pi_number'), name='uq_jobwork_pi_number'),
        ),
    ]
