# Generated by Django 5.2.7 on 2026-10-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobwork', '0002_vendorprocessinstruction_vpiprogressentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processplan',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processplan',
            name='approver',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processplan',
            name='assigned_employee',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processplan',
            name='contact_person',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processplan',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processplan',
            name='expected_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processplan',
            name='finished_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='processplan',
            name='grey_lot_no',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processplan',
            name='no_of_rolls',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processplan',
            name='phone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processplan',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processplan',
            name='taka_roll_no',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processplan',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
    ]
