# Generated by Django 5.2.7 on 2026-10-07 09:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('jobwork', '0004_plancharge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JWOReprocess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('no', models.TextField(default='')),
                ('inward_no', models.TextField(default='')),
                ('date', models.DateField()),
                ('qty', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('reason', models.TextField(default='')),
                ('expected_return', models.DateField(blank=True, null=True)),
                ('status', models.TextField(default='Pending')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job_work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reprocesses', to='jobwork.jobworkorder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobwork_reprocesses',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
