# Generated by Django 5.2.7 on 2026-10-07 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('jobwork', '0005_jworeprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpiprogressentry',
            name='photo_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.file'),
        ),
    ]
