# Generated by Django 5.2.7 on 2026-10-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='applies_to',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='holiday',
            name='holiday_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='holiday',
            name='status',
            field=models.TextField(default='Upcoming'),
        ),
        migrations.AddField(
            model_name='resignation',
            name='handover_to',
            field=models.TextField(blank=True, null=True),
        ),
    ]
