# Generated by Django 5.2.7 on 2026-09-25 05:16

import apps.accounts.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.TextField()),
                ('phone', models.TextField(blank=True, null=True)),
                ('avatar_url', models.TextField(blank=True, null=True)),
                ('department', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('status', models.TextField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Invited', 'Invited'), ('Deleted', 'Deleted')], default='Active')),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('failed_login_count', models.IntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('crm_roles', models.JSONField(blank=True, default=list)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('legacy_id', models.TextField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['name'],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('plan', models.TextField(default='Standard')),
                ('status', models.TextField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Cancelled', 'Cancelled')], default='Active')),
                ('timezone', models.TextField(default='Asia/Kolkata')),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('fy_start_month', models.SmallIntegerField(default=4)),
                ('onboarded_on', models.DateField(blank=True, null=True)),
                ('contact_name', models.TextField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.TextField(blank=True, null=True)),
                ('industry', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_demo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('legacy_id', models.TextField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'clients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.TextField(unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'password_reset_tokens',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('module', models.TextField()),
                ('group', models.TextField()),
                ('label', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'permissions',
                'ordering': ['module', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.TextField()),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_system', models.BooleanField(default=False)),
                ('legacy_id', models.TextField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'role_permissions',
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effect', models.TextField(choices=[('grant', 'grant'), ('deny', 'deny')])),
            ],
            options={
                'db_table': 'user_permissions',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refresh_token_hash', models.TextField(unique=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('device_label', models.TextField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_sessions',
                'ordering': ['-last_seen_at'],
            },
        ),
    ]
