# Generated by Django 5.2.7 on 2026-09-25 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0003_initial'),
        ('accounts', '0002_initial'),
        ('masters', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itemserial',
            name='warranty_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sales.warrantycard'),
        ),
        migrations.AddField(
            model_name='documentlineserial',
            name='serial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='line_links', to='masters.itemserial'),
        ),
        migrations.AddField(
            model_name='location',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.client'),
        ),
        migrations.AddField(
            model_name='location',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='masters.location'),
        ),
        migrations.AddField(
            model_name='location',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemserial',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='masters.location'),
        ),
        migrations.AddField(
            model_name='item',
            name='default_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='masters.location'),
        ),
        migrations.AddField(
            model_name='party',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.client'),
        ),
        migrations.AddField(
            model_name='party',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='party',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='party',
            name='ledger_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='party',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_items', to='masters.party'),
        ),
        migrations.AddField(
            model_name='partycontact',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.client'),
        ),
        migrations.AddField(
            model_name='partycontact',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partycontact',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partycontact',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='masters.party'),
        ),
        migrations.AddField(
            model_name='partycontact',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unit',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.client'),
        ),
        migrations.AddField(
            model_name='unit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unit',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unit',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='itemcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('client', 'code'), name='uq_item_categories_code'),
        ),
        migrations.AddConstraint(
            model_name='categorypart',
            constraint=models.UniqueConstraint(fields=('category', 'item'), name='uq_category_parts'),
        ),
        migrations.AddConstraint(
            model_name='categorycustomfield',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type', 'dropdown'), _negated=True), ('options__isnull', False), _connector='OR'), name='ck_ccf_options'),
        ),
        migrations.AddConstraint(
            model_name='itempart',
            constraint=models.UniqueConstraint(fields=('parent_item', 'part_item'), name='uq_item_parts'),
        ),
        migrations.AddConstraint(
            model_name='itempart',
            constraint=models.CheckConstraint(condition=models.Q(('parent_item', models.F('part_item')), _negated=True), name='ck_item_parts_no_self'),
        ),
        migrations.AddConstraint(
            model_name='itempart',
            constraint=models.CheckConstraint(condition=models.Q(('required_qty__gt', 0)), name='ck_item_parts_qty'),
        ),
        migrations.AddIndex(
            model_name='documentlineserial',
            index=models.Index(fields=['serial'], name='ix_dls_serial'),
        ),
        migrations.AddConstraint(
            model_name='documentlineserial',
            constraint=models.UniqueConstraint(fields=('line_table', 'line_id', 'serial'), name='uq_document_line_serials'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('client', 'code'), name='uq_locations_code'),
        ),
        migrations.AddIndex(
            model_name='itemserial',
            index=models.Index(fields=['client', 'item', 'status'], name='ix_item_serials_status'),
        ),
        migrations.AddConstraint(
            model_name='itemserial',
            constraint=models.UniqueConstraint(fields=('client', 'item', 'serial_no'), name='uq_item_serials'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['client', 'type'], name='ix_parties_type'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['client', 'name'], name='ix_parties_name'),
        ),
        migrations.AddConstraint(
            model_name='party',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('client', 'code'), name='uq_parties_code'),
        ),
        migrations.AddConstraint(
            model_name='party',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('gstin__isnull', False)), fields=('client', 'gstin'), name='uq_parties_gstin'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['client', 'category'], name='ix_items_category'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['client', 'sku'], name='ix_items_sku'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['client', 'item_kind'], name='ix_items_kind'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('client', 'sku'), name='uq_items_sku'),
        ),
        migrations.AddConstraint(
            model_name='partycontact',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_primary', True)), fields=('party',), name='uq_party_primary_contact'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('client', 'code'), name='uq_units_code'),
        ),
    ]
