# Generated by Django 5.2.7 on 2026-10-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='vendor_type',
            field=models.TextField(blank=True, choices=[('Manufacturing', 'Manufacturing'), ('Dyeing - Other Process', 'Dyeing - Other Process')], null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='type',
            field=models.TextField(choices=[('Customer', 'Customer'), ('Vendor', 'Vendor'), ('Both', 'Both'), ('Transporter', 'Transporter')], default='Customer'),
        ),
    ]
