# Generated by Django 5.2.7 on 2026-10-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_party_vendor_type_alter_party_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='vehicle_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='vehicle_capacity_unit',
            field=models.TextField(blank=True, choices=[('Tons', 'Tons'), ('Kg', 'Kg'), ('Litres', 'Litres')], null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='vehicle_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='vehicle_type',
            field=models.TextField(blank=True, choices=[('Truck', 'Truck'), ('Mini Truck / LCV', 'Mini Truck / LCV'), ('Trailer', 'Trailer'), ('Container', 'Container'), ('Tanker', 'Tanker'), ('Tempo', 'Tempo'), ('Other', 'Other')], null=True),
        ),
    ]
