# Generated by Django 5.2.7 on 2026-10-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_party_vehicle_capacity_party_vehicle_capacity_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='vehicle_capacity_unit',
            field=models.TextField(blank=True, choices=[('Tons', 'Tons'), ('Kg', 'Kg'), ('Litres', 'Litres'), ('Taka', 'Taka')], null=True),
        ),
    ]
