# Generated by Django 5.2.7 on 2026-10-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_alter_party_vehicle_capacity_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='fabric_color',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='fabric_design',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='fabric_gsm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='fabric_quality',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='fabric_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_kind',
            field=models.TextField(choices=[('Machine', 'Machine'), ('Part', 'Part'), ('Standalone', 'Standalone'), ('Service', 'Service'), ('Component', 'Component'), ('Consumable', 'Consumable'), ('Fabric', 'Fabric')], default='Standalone'),
        ),
    ]
