# Generated by Django 5.2.7 on 2026-09-25 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_initial'),
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='journalline',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_lines', to='masters.party'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('client', 'code'), name='uq_coa_code'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('system_key__isnull', False)), fields=('client', 'system_key'), name='uq_coa_system_key'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('client', 'account', 'period_start', 'period_end'), name='uq_budgets_period'),
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('client', 'name'), name='uq_expense_categories_name'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['client', 'source_document_type', 'source_document_id'], name='ix_journal_source'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['client', '-entry_date'], name='ix_journal_date'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('client', 'entry_number'), name='uq_journal_number'),
        ),
        migrations.AddConstraint(
            model_name='banktransfer',
            constraint=models.CheckConstraint(condition=models.Q(('from_account', models.F('to_account')), _negated=True), name='ck_bank_transfer_accounts'),
        ),
        migrations.AddConstraint(
            model_name='banktransfer',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_bank_transfer_amount'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['client', 'account', 'journal_entry'], name='ix_journal_lines_account'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(condition=models.Q(('party__isnull', False)), fields=['client', 'party'], name='ix_journal_lines_party'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('credit', 0), ('debit__gt', 0)), models.Q(('credit__gt', 0), ('debit', 0)), _connector='OR'), name='ck_journal_line_one_side'),
        ),
    ]
