# Generated by Django 5.2.7 on 2026-09-25 05:16

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityStandard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.TextField()),
                ('checklist', models.JSONField(blank=True, default=list)),
                ('tolerance_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'quality_standards',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('legacy_id', models.TextField(blank=True, db_index=True, null=True)),
                ('ticket_number', models.TextField()),
                ('job_reference', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('technician', models.TextField(blank=True, null=True)),
                ('used_on', models.DateField()),
                ('chargeable', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_usage',
                'ordering': ['-used_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('legacy_id', models.TextField(blank=True, db_index=True, null=True)),
                ('audit_number', models.TextField()),
                ('period_month', models.DateField()),
                ('status', models.TextField(choices=[('Draft', 'Draft'), ('Counting', 'Counting'), ('Posted', 'Posted'), ('Cancelled', 'Cancelled')], default='Draft')),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock_audits',
                'ordering': ['-period_month'],
            },
        ),
        migrations.CreateModel(
            name='StockAuditLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('system_qty', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('counted_qty', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('variance', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('counted_qty'), '-', models.F('system_qty')), output_field=models.DecimalField(decimal_places=4, max_digits=18))),
                ('reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock_audit_lines',
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('on_hand', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('damaged', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('inward_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('inward_qty', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
            ],
            options={
                'db_table': 'stock_balances',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('legacy_id', models.TextField(blank=True, db_index=True, null=True)),
                ('type', models.TextField(choices=[('PURCHASE', 'PURCHASE'), ('PURCHASE_RETURN', 'PURCHASE_RETURN'), ('PURCHASE_REVERSAL', 'PURCHASE_REVERSAL'), ('SALE', 'SALE'), ('SALE_REVERSAL', 'SALE_REVERSAL'), ('SALES_RETURN', 'SALES_RETURN'), ('RETURN_CANCELLATION', 'RETURN_CANCELLATION'), ('TRANSFER_IN', 'TRANSFER_IN'), ('TRANSFER_OUT', 'TRANSFER_OUT'), ('ADJUSTMENT', 'ADJUSTMENT'), ('FAULTY', 'FAULTY'), ('SERVICE_USAGE', 'SERVICE_USAGE'), ('ZONE_ISSUE', 'ZONE_ISSUE')])),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('weighed_qty', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('reference_type', models.TextField(blank=True, null=True)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('reference_number', models.TextField(blank=True, null=True)),
                ('source_document_type', models.TextField(blank=True, null=True)),
                ('source_document_id', models.UUIDField(blank=True, null=True)),
                ('batch_number', models.TextField(blank=True, null=True)),
                ('movement_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock_movements',
                'ordering': ['-movement_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('legacy_id', models.TextField(blank=True, db_index=True, null=True)),
                ('transfer_number', models.TextField()),
                ('transfer_date', models.DateField()),
                ('status', models.TextField(choices=[('Requested', 'Requested'), ('In Transit', 'In Transit'), ('Received', 'Received'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Requested')),
                ('shipped_by', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock_transfers',
                'ordering': ['-transfer_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransferLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('qty', models.DecimalField(decimal_places=4, max_digits=18)),
                ('received_qty', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
            ],
            options={
                'db_table': 'stock_transfer_lines',
            },
        ),
        migrations.CreateModel(
            name='ZoneRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('legacy_id', models.TextField(blank=True, db_index=True, null=True)),
                ('request_number', models.TextField()),
                ('target_sector', models.TextField(blank=True, null=True)),
                ('requested_by_name', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('request_date', models.DateField(blank=True, null=True)),
                ('status', models.TextField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Fulfilled', 'Fulfilled'), ('Rejected', 'Rejected')], default='Requested')),
                ('reject_reason', models.TextField(blank=True, null=True)),
                ('manager_signoff_needed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'zone_requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ZoneRequestLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('requested_qty', models.DecimalField(decimal_places=4, max_digits=18)),
                ('issued_qty', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
            ],
            options={
                'db_table': 'zone_request_lines',
            },
        ),
        migrations.CreateModel(
            name='FaultyPart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('legacy_id', models.TextField(blank=True, db_index=True, null=True)),
                ('rma_number', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=18)),
                ('reported_date', models.DateField()),
                ('fault_description', models.TextField(blank=True, null=True)),
                ('status', models.TextField(choices=[('Reported', 'Reported'), ('Pending Action', 'Pending Action'), ('Sent for Replacement', 'Sent for Replacement'), ('Replaced', 'Replaced'), ('Credited', 'Credited'), ('Closed', 'Closed')], default='Reported')),
                ('notes', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'faulty_parts',
                'ordering': ['-reported_date', '-created_at'],
            },
        ),
    ]
