# Generated by Django 5.2.7 on 2026-09-25 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('inventory', '0002_initial'),
        ('masters', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceusage',
            name='warranty_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sales.warrantycard'),
        ),
        migrations.AddField(
            model_name='stockaudit',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.client'),
        ),
        migrations.AddField(
            model_name='stockaudit',
            name='conducted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockaudit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockaudit',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockaudit',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='masters.location'),
        ),
        migrations.AddField(
            model_name='stockaudit',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockauditline',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.client'),
        ),
        migrations.AddField(
            model_name='stockauditline',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockauditline',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockauditline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.item'),
        ),
        migrations.AddField(
            model_name='stockauditline',
            name='stock_audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockaudit'),
        ),
        migrations.AddField(
            model_name='stockauditline',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockbalance',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.client'),
        ),
        migrations.AddField(
            model_name='stockbalance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockbalance',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockbalance',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='masters.item'),
        ),
        migrations.AddField(
            model_name='stockbalance',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='masters.location'),
        ),
        migrations.AddField(
            model_name='stockbalance',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.client'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='masters.item'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='masters.location'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='original_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.stockmovement'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reversal_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.stockmovement'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockauditline',
            name='adjustment_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.stockmovement'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.client'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='from_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='masters.location'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='to_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='masters.location'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransferline',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.client'),
        ),
        migrations.AddField(
            model_name='stocktransferline',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransferline',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransferline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.item'),
        ),
        migrations.AddField(
            model_name='stocktransferline',
            name='stock_transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stocktransfer'),
        ),
        migrations.AddField(
            model_name='stocktransferline',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zonerequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zonerequest',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.client'),
        ),
        migrations.AddField(
            model_name='zonerequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zonerequest',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zonerequest',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zonerequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zonerequest',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zonerequest',
            name='zone_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zone_requests', to='masters.location'),
        ),
        migrations.AddField(
            model_name='zonerequestline',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.client'),
        ),
        migrations.AddField(
            model_name='zonerequestline',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zonerequestline',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zonerequestline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.item'),
        ),
        migrations.AddField(
            model_name='zonerequestline',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zonerequestline',
            name='zone_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.zonerequest'),
        ),
        migrations.AddConstraint(
            model_name='faultypart',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('client', 'rma_number'), name='uq_rma_number'),
        ),
        migrations.AddConstraint(
            model_name='serviceusage',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('client', 'ticket_number'), name='uq_service_usage_ticket'),
        ),
        migrations.AddConstraint(
            model_name='stockaudit',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('client', 'audit_number'), name='uq_audit_number'),
        ),
        migrations.AddIndex(
            model_name='stockbalance',
            index=models.Index(fields=['client', 'item'], name='ix_stock_balances_item'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.UniqueConstraint(fields=('client', 'item', 'location'), name='uq_stock_balances'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['client', 'item', 'location', 'movement_date'], name='ix_movements_item'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['client', 'reference_type', 'reference_id'], name='ix_movements_ref'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['client', '-movement_date'], name='ix_movements_date'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity', 0), _negated=True), name='ck_movement_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('reference_id__isnull', False), ('type', 'ADJUSTMENT'), _connector='OR'), name='ck_movement_reference'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type', 'ADJUSTMENT'), _negated=True), ('notes__isnull', False), _connector='OR'), name='ck_movement_adjustment_reason'),
        ),
        migrations.AddConstraint(
            model_name='stocktransfer',
            constraint=models.CheckConstraint(condition=models.Q(('from_location', models.F('to_location')), _negated=True), name='ck_transfer_locations'),
        ),
        migrations.AddConstraint(
            model_name='stocktransfer',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('client', 'transfer_number'), name='uq_transfer_number'),
        ),
        migrations.AddConstraint(
            model_name='stocktransferline',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='ck_stl_qty'),
        ),
        migrations.AddConstraint(
            model_name='zonerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('client', 'request_number'), name='uq_zone_request_number'),
        ),
    ]
