# Generated by Django 5.2.7 on 2026-10-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_stagetask_repeats_integer'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadproduct',
            name='expected_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='leadproduct',
            name='fabric_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadproduct',
            name='fabric_color',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadproduct',
            name='fabric_design',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadproduct',
            name='fabric_gsm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='leadproduct',
            name='fabric_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadproduct',
            name='fabric_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='leadproduct',
            name='status',
            field=models.TextField(default='Active'),
        ),
        migrations.AddField(
            model_name='leadproduct',
            name='uom',
            field=models.TextField(blank=True, null=True),
        ),
    ]
