# Generated by Django 5.2.7 on 2026-10-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_leadproduct_expected_rate_leadproduct_fabric_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crmproject',
            name='customer_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crmproject',
            name='owner_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crmproject',
            name='project_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crmproject',
            name='team',
            field=models.TextField(blank=True, null=True),
        ),
    ]
