# Generated by Django 5.2.7 on 2026-10-08 10:57

from django.db import migrations, models


def _migrate_call_again(apps, schema_editor):
    Task = apps.get_model("crm", "Task")
    Task.objects.filter(next_action="call-again").update(next_action="follow-up")


def _reverse_call_again(apps, schema_editor):
    Task = apps.get_model("crm", "Task")
    Task.objects.filter(next_action="follow-up").update(next_action="call-again")


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_lead_conversion'),
    ]

    operations = [
        migrations.RunPython(_migrate_call_again, _reverse_call_again),
        migrations.AlterField(
            model_name='task',
            name='next_action',
            field=models.TextField(blank=True, choices=[('follow-up', 'follow-up'), ('schedule-demo', 'schedule-demo'), ('send-quotation', 'send-quotation'), ('move-next-stage', 'move-next-stage'), ('finish', 'finish')], null=True),
        ),
        migrations.DeleteModel(
            name='LeadCall',
        ),
    ]
