# Generated by Django 5.2.7 on 2026-10-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.TextField(choices=[('Draft', 'Draft'), ('Issued', 'Issued'), ('Pending', 'Pending'), ('Received', 'Received'), ('Cancelled', 'Cancelled'), ('Pending Approval', 'Pending Approval'), ('Approved', 'Approved'), ('In Production', 'In Production'), ('Partially Received', 'Partially Received'), ('Fully Received', 'Fully Received')], default='Draft'),
        ),
    ]
