# Generated by Django 5.2.7 on 2026-10-06 05:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('core', '0001_initial'),
        ('masters', '0008_fabric_items'),
        ('purchase', '0002_alter_purchaseorder_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('legacy_id', models.TextField(blank=True, db_index=True, null=True)),
                ('vendor_bill_number', models.TextField()),
                ('bill_date', models.DateField()),
                ('party_name', models.TextField(blank=True, null=True)),
                ('gst_pct', models.DecimalField(decimal_places=4, default=5, max_digits=7)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.TextField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending')),
                ('match_status', models.TextField(choices=[('Pending Matching', 'Pending Matching'), ('Matched', 'Matched')], default='Pending Matching')),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.file')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('goods_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_bills', to='purchase.goodsreceipt')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_bills', to='masters.party')),
                ('purchase_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_bills', to='purchase.purchasebill')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_bills', to='purchase.purchaseorder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'purchase_vendor_bills',
                'ordering': ['-bill_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorBillLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('line_no', models.IntegerField(default=1)),
                ('sku', models.TextField(blank=True, null=True)),
                ('item_name', models.TextField(blank=True, null=True)),
                ('uom', models.TextField(blank=True, null=True)),
                ('qty', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('rate', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.item')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vendor_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='purchase.vendorbill')),
            ],
            options={
                'db_table': 'purchase_vendor_bill_lines',
                'ordering': ['line_no'],
            },
        ),
        migrations.AddIndex(
            model_name='vendorbill',
            index=models.Index(fields=['client', 'status'], name='ix_vendor_bills_status'),
        ),
        migrations.AddIndex(
            model_name='vendorbill',
            index=models.Index(fields=['client', 'match_status'], name='ix_vendor_bills_match'),
        ),
        migrations.AddConstraint(
            model_name='vendorbill',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('client', 'vendor_bill_number'), name='uq_vendor_bill_number'),
        ),
        migrations.AddIndex(
            model_name='vendorbillline',
            index=models.Index(fields=['item', 'vendor_bill'], name='ix_vendor_bill_lines_item'),
        ),
        migrations.AddConstraint(
            model_name='vendorbillline',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('vendor_bill', 'line_no'), name='uq_vendor_bill_line_no'),
        ),
    ]
